name = "FreqTools"
uuid = "fb344015-2583-4870-9d87-af59fc8caa54"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
FreqTables = "da1fdf0e-e0ff-5433-a45f-9bb5ff651cb1"
NamedArrays = "86f7a689-2022-50b4-a561-43c23ac3c673"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
TableMetadataTools = "9ce81f87-eacc-4366-bf80-b621a3098ee2"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
StatsAPI = "82ae8749-77ed-4fe6-ae5f-f523153014b0"

[compat]
julia = ">=1.6"
DataFrames = ">=1.7"
PrettyTables = ">=2.0"
Printf = ">=0.5"
FreqTables = ">=1.0"
NamedArrays = ">=0.9"
CategoricalArrays = ">=0.5"
TableMetadataTools = ">=0.1"
Reexport = ">=1.0"
Distributions = ">=0.2"
StatsAPI = ">=1.0"

[extras]

[targets]
